#Persisted by DefaultConfig
#Fri May 16 20:09:06 CST 2025
ratehawk.query.price.cache.qps=0.16
query.cache.supplier=[10005]
ratehawk.query.price.queue.task.return=1
didatravel.query.cache=true
expedia.query.price.cache.qps=10
supplier.hotel.cache.map={10005\:["16024166"]}
ratehawk.query.price.queue.task.switch=1
expedia.query.price.queue.task.return=1
expedia.commission.rate=0.525
supplier.query.timezone=["10005"]
expedia.query.price.queue.task.switch=1
