
    topic: test
    #sync tag(同步消息tag)
    sync-tag: sync-tags
    #async tag(异步消息tag)
    async-tag: async-tags
    #oneway tag(单向消息tag)
    oneway-tag: oneway-tags

  consumer:
    group: test
    #监听主题
    topic: test
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  hotel:
    group: hotel_consumer_group
    topic: hotel_order_topic
  room:
    group: room_consumer_group
    topic: room_order_topic
  product:
    group: product_consumer_group
    topic: product_order_topic

  enhance:
    # 启动隔离，用于激活配置类EnvironmentIsolationConfig
    # 启动后会自动在topic上拼接激活的配置文件，达到自动隔离的效果
    enabledIsolation: true
    # 隔离环境名称，拼接到topic后，topic_dev，默认空字符串
    environment: dev
travelconnect:
  url:
    search: http://develop2.webapi.travelconnect.co/api/hotel/2c/search/zh-cn
    hotel: http://develop2.webapi.travelconnect.co/api/hotel/2c/hotel/detail
    prebook: http://develop2.webapi.travelconnect.co/api/hotel/2c/order/prebook/zh-cn
  companyId: TC0143
  signKey: 81708dbaf8b23ca0cd2b8d36345534bf
aichotels:
  url:
    host: https://api.aichotels.net.cn
    hotelList: /content/public/hotelinfo_list
    singleHotel: /content/public/single_hotel
    cityList: /content/public/city_list
    rooms: /content/public/hotel_rooms
    availability: /rate/public/cache/room_availability
    prebook: /rate/public/booking/prebook
  apiClientKey: BeijingBaosheng
  secret: SRLxRgRXjjaPCWUbcWcwriusUNtpYe3VxRg9