server:
  port: 8080
spring:
  application:
    name: trip-booking-spa
  sleuth:
    hystrix:
      strategy:
        enabled: false
  profiles:
    active: dev,mapper

logging:
  config: classpath:log4j2.xml
  level:
    root: info

#-------------------------------prometheus开启健康检查端点--------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,service-registry,prometheus,health-service"
