#Persisted by DefaultConfig
#Tue May 28 18:16:06 CST 2024
meituan.check.ratio=1.02
fliggy.cps.fixed.date.query.limit=10
fliggy.distrib.cookie="4534534"
distribute.real.check={"30002"\:1}
fliggy.check.timeout=10000
fliggy.cps.query.limit=70
fliggy.reset.switch=1
test=1
product.date.map={1\:"1,2,3,4,5,6,7,8,9,10",2\:"4,5,6"}
fliggy.distrib.pushPriceUpdateSwitch=0
check.wx.time.out=1
dingding.request.list="045562533421313384"
wx.request.list="BaoYongSheng"
product.filter.keywords="TMC,\u5546\u65C5\u4E13\u4EAB"
check.to.cache=2
sell.hotel.list=""
fliggy.distrib.markupRate=6.0
fliggy.distrib.token="63463"
