server:
  port: 8080

spring:
  datasource:
    host: pc-2ze0t0vwxj392d111.mysql.polardb.rds.aliyuncs.com
    port: 3306
    name: intl_bg_admin
    username: dbadmin
    password: VvTUbbEp$D6uGiLDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
  redis:
    host: r-2ze1teeyudubm0dw8u.redis.rds.aliyuncs.com
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 32
        min-idle: 4
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心地址
        server-addr: 10.18.0.8:8848
        # 分组，不同分组之间不能调用，用于微服务之间的隔离
        group: DEFAULT_GROUP
        # 生产环境
        namespace: prod

        # Nacos 认证用户
        username: nacos-prod
        # Nacos 认证密码
        password: zaq1xsw2
        config:
          # 是否开启配置中心 默认true
          enabled: true
          # 指定Nacos配置中心的地址
          server-addr: 10.18.0.8:8848
          # 区分环境：开发环境、测试环境、预发布环境、⽣产环境
          namespace: prod
          # 区分不同应⽤：同⼀个环境内，不同应⽤的配置，通过group来区分。
          group: DEFAULT_GROUP
          #指定yaml格式的配置 默认properties
          file-extension: yaml
          # 自动刷新配置文件,默认true
          refresh-enabled: true
          # Nacos 认证用户
          username: nacos-prod
          # Nacos 认证密码
          password: zaq1xsw2
          # 配置文件prefix
          prefix: ${spring.application.name}

  schedulerx2:
    endpoint: addr-bj-internal.edas.aliyun.com
    namespace: bcf3aaf8-8eca-459d-971e-ab8a3884eba0
    groupId: bingo-hotel-spa-intl
    appKey: YkeT7pKCVanNmiay6AGmrxg

management:
  endpoints:
    web:
      exposure:
        include: prometheus

#apollo相关配置 开始#
app:
  # 与Apollo Portal上面创建的app id保持一致
  id: bingo-hotel-spa-intl
# 项目启动时需要添加启动参数 -Denv=DEV 来指定 apollo环境
apollo:
  # 就是apollo config server的地址
  meta: http://10.18.1.51:8080
  bootstrap:
    # 是否开启 Apollo
    enabled: true
    eagerLoad:
      # 将 Apollo 加载提到初始化日志系统之前，如果设置为false，则配置中心中修改日志信息不会生效
      enabled: true
    namespaces: application
  cacheDir: ./config
  # 刷新时间,单位：分钟，默认5
  refreshInterval: 5
  config-service: http://10.18.1.51:8080
#对应apollo配置中心环境
env: prod
#apollo相关配置 结束#
travelconnect:
  url:
    search: https://b2c-nanhwa.travelconnect.co//api/hotel/2c/search/zh-cn
    hotel: https://b2c-nanhwa.travelconnect.co//api/hotel/2c/hotel/detail
    prebook: https://b2c-nanhwa.travelconnect.co//api/hotel/2c/order/prebook/zh-cn
  companyId: TC0143
  signKey: 02706c54a917a6940cdf3f283a860e58
aichotels:
  url:
    host: https://api.aichotels.net.cn
    hotelList: /content/public/hotelinfo_list
    singleHotel: /content/public/single_hotel
    cityList: /content/public/city_list
    rooms: /content/public/hotel_rooms
    availability: /rate/public/search/room_availability
    prebook: /rate/public/booking/prebook
  apiClientKey: BeijingBaosheng
  secret: SRLxRgRXjjaPCWUbcWcwriusUNtpYe3VxRg9
didatravel:
  licenseKey: BSYX_key0509
  clientId: BSYX
  localFilePath: /home/webrun/logs/file
huitravel:
  url:
    hotellist: http://hapi.huizhi-intl.com/hotelsell/cithotelsell/yoppay/static/hotellist
    hoteldetails: http://hapi.huizhi-intl.com/hotelsell/cithotelsell/yoppay/static/hoteldetails
    getPrice: http://hapi.huizhi-intl.com/hotelsell/cithotelsell/yoppay/getrateplanprice
    checkavailability: http://hapi.huizhi-intl.com/hotelsell/cithotelsell/yoppay/checkavailability
  appkey: bsgl
  secretKey: C340EB9BF816799573229D66B6F11555
expedia:
  apiKey: 6urn54ijk30uttcqm64c3it6gf
  sharedSecret: 708a6tdaqvm7
  session: abcdefg
  ownIp: 5.5.5.5
  localFilePath: /home/webrun/logs/file
  partner_point_of_sale: B2B_SA_PKG_MOD_VCC
  payment_terms: 1
  billing_terms: VCC
  url:
    host: https://test.ean.com
fliggy:
  distrib:
    url: http://gw.api.taobao.com/router/rest
    sessionKey: 6100528c57015c382fc6cb6b4049d1d001b91c145dc5d792217553435874
    appKey: 34784001
    appSecret: c4b6ee3e5015cee006a75aa8acd66275