CREATE TABLE IF NOT EXISTS expedia_property_content (
    property_id VARCHAR(32) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    name VARCHAR(512) NULL,
    country_code CHAR(2) NULL,
    city VARCHAR(255) NULL,
    latitude DECIMAL(10, 7) NULL,
    longitude DECIMAL(10, 7) NULL,
    star_rating DECIMAL(3, 1) NULL,
    source_added_at DATETIME(3) NULL,
    source_updated_at DATETIME(3) NULL,
    fetched_at DATETIME(3) NOT NULL,
    raw_sha256 CHAR(64) NOT NULL,
    mapping_version VARCHAR(64) NOT NULL,
    raw_json JSON NOT NULL,
    normalized_json JSON NOT NULL,
    evidence_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (property_id),
    KEY idx_expedia_property_country_city (country_code, city),
    KEY idx_expedia_property_source_updated (source_updated_at),
    KEY idx_expedia_property_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
